import React, { useState, useEffect, useMemo } from 'react';
import { X, CheckCircle2, AlertTriangle, TrendingUp, Clock, Filter, ArrowUpRight, ArrowDownRight, ShieldCheck } from 'lucide-react';
import { getSignals, getSignalStats, evaluateOpenSignals } from '../../services/signalTracker.js';

/**
 * GlobalSignalTrackerModal
 * Allows investors to audit all historical and active quantitative signals
 * generated by Drabyashree NEPSE, verifying real out-of-sample accuracy.
 */
export function GlobalSignalTrackerModal({ isOpen = true, onClose, marketStocks = [], inlineMode = false }) {
  const [filterStatus, setFilterStatus] = useState('ALL');
  const [signals, setSignals] = useState([]);
  const [stats, setStats] = useState(null);

  const loadData = () => {
    if (marketStocks.length > 0) {
      evaluateOpenSignals(marketStocks);
    }
    const all = getSignals();
    all.sort((a, b) => new Date(b.signalDate) - new Date(a.signalDate));
    setSignals(all);
    setStats(getSignalStats());
  };

  useEffect(() => {
    if (isOpen) {
      loadData();
    }
  }, [isOpen, marketStocks]);

  const filteredSignals = useMemo(() => {
    if (filterStatus === 'ALL') return signals;
    if (filterStatus === 'OPEN') return signals.filter(s => s.status === 'open');
    if (filterStatus === 'HIT_TARGET') return signals.filter(s => s.status === 'hit_target');
    if (filterStatus === 'HIT_STOP') return signals.filter(s => s.status === 'hit_stop');
    if (filterStatus === 'EXPIRED') return signals.filter(s => s.status === 'expired');
    return signals;
  }, [signals, filterStatus]);

  if (!isOpen) return null;

  const content = (
    <div style={{
      background: '#0f172a',
      border: '1px solid rgba(255,255,255,0.1)',
      borderRadius: 16,
      width: '100%',
      maxWidth: inlineMode ? '100%' : 720,
      maxHeight: inlineMode ? 'none' : '90vh',
      display: 'flex',
      flexDirection: 'column',
      boxShadow: inlineMode ? 'none' : '0 20px 40px rgba(0,0,0,0.6)',
      overflow: 'hidden'
    }}>
      {/* Header */}
      <div style={{
        padding: '16px 20px',
        borderBottom: '1px solid rgba(255,255,255,0.08)',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        background: '#151922'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <div style={{
            width: 34, height: 34, borderRadius: 10,
            background: 'rgba(16, 185, 129, 0.15)',
            border: '1px solid rgba(16, 185, 129, 0.3)',
            display: 'flex', alignItems: 'center', justifyContent: 'center'
          }}>
            <ShieldCheck style={{ width: 18, height: 18, color: '#34d399' }} />
          </div>
          <div>
            <div style={{ fontSize: 15, fontWeight: 900, color: '#ffffff' }}>
              Algorithmic Signal Track Record
            </div>
            <div style={{ fontSize: 11, color: '#94a3b8' }}>
              Verified historical performance of generated setup plans
            </div>
          </div>
        </div>

        {onClose && !inlineMode && (
          <button
            onClick={onClose}
            style={{
              background: 'rgba(255,255,255,0.06)',
              border: '1px solid rgba(255,255,255,0.1)',
              borderRadius: 8,
              width: 32, height: 32,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              color: '#94a3b8',
              cursor: 'pointer'
            }}
          >
            <X style={{ width: 16, height: 16 }} />
          </button>
        )}
      </div>

      {/* Aggregate Stats Cards */}
        {stats && (
          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(110px, 1fr))',
            gap: 10,
            padding: '16px 20px',
            background: 'rgba(0,0,0,0.3)',
            borderBottom: '1px solid rgba(255,255,255,0.06)'
          }}>
            <div style={{ background: 'rgba(255,255,255,0.03)', padding: 10, borderRadius: 10, border: '1px solid rgba(255,255,255,0.05)' }}>
              <div style={{ fontSize: 10, color: '#94a3b8', textTransform: 'uppercase', fontWeight: 800 }}>Total Signals</div>
              <div style={{ fontSize: 18, fontWeight: 900, color: '#ffffff', fontFamily: 'var(--font-mono)', marginTop: 2 }}>{stats.total}</div>
              <div style={{ fontSize: 9.5, color: '#64748b' }}>{stats.openCount} Open • {stats.closedCount} Closed</div>
            </div>

            <div style={{ background: 'rgba(255,255,255,0.03)', padding: 10, borderRadius: 10, border: '1px solid rgba(255,255,255,0.05)' }}>
              <div style={{ fontSize: 10, color: '#94a3b8', textTransform: 'uppercase', fontWeight: 800 }}>Win Rate</div>
              <div style={{
                fontSize: 18, fontWeight: 900,
                color: (stats.winRate || 0) >= 50 ? '#34d399' : '#f87171',
                fontFamily: 'var(--font-mono)', marginTop: 2
              }}>
                {stats.closedCount > 0 ? `${stats.winRate.toFixed(1)}%` : '—'}
              </div>
              <div style={{ fontSize: 9.5, color: '#64748b' }}>Target Hit vs Stop</div>
            </div>

            <div style={{ background: 'rgba(255,255,255,0.03)', padding: 10, borderRadius: 10, border: '1px solid rgba(255,255,255,0.05)' }}>
              <div style={{ fontSize: 10, color: '#94a3b8', textTransform: 'uppercase', fontWeight: 800 }}>Avg Return</div>
              <div style={{
                fontSize: 18, fontWeight: 900,
                color: (stats.avgReturnPct || 0) >= 0 ? '#34d399' : '#f87171',
                fontFamily: 'var(--font-mono)', marginTop: 2
              }}>
                {stats.closedCount > 0 ? `${(stats.avgReturnPct || 0) >= 0 ? '+' : ''}${stats.avgReturnPct}%` : '—'}
              </div>
              <div style={{ fontSize: 9.5, color: '#64748b' }}>Across closed setups</div>
            </div>

            <div style={{ background: 'rgba(255,255,255,0.03)', padding: 10, borderRadius: 10, border: '1px solid rgba(255,255,255,0.05)' }}>
              <div style={{ fontSize: 10, color: '#94a3b8', textTransform: 'uppercase', fontWeight: 800 }}>Best Trade</div>
              <div style={{ fontSize: 14, fontWeight: 900, color: '#34d399', fontFamily: 'var(--font-mono)', marginTop: 4 }}>
                {stats.bestTrade?.symbol ? `${stats.bestTrade.symbol} (+${stats.bestTrade.returnPct}%)` : '—'}
              </div>
              <div style={{ fontSize: 9.5, color: '#64748b' }}>Top recorded gain</div>
            </div>
          </div>
        )}

        {/* Filter Tabs */}
        <div style={{
          display: 'flex',
          gap: 6,
          padding: '10px 20px',
          borderBottom: '1px solid rgba(255,255,255,0.06)',
          overflowX: 'auto'
        }}>
          {[
            { id: 'ALL', label: `All (${signals.length})` },
            { id: 'OPEN', label: `Open (${signals.filter(s => s.status === 'open').length})` },
            { id: 'HIT_TARGET', label: `Hit Target (${signals.filter(s => s.status === 'hit_target').length})` },
            { id: 'HIT_STOP', label: `Hit Stop (${signals.filter(s => s.status === 'hit_stop').length})` },
            { id: 'EXPIRED', label: `Expired (${signals.filter(s => s.status === 'expired').length})` },
          ].map(tab => (
            <button
              key={tab.id}
              onClick={() => setFilterStatus(tab.id)}
              style={{
                background: filterStatus === tab.id ? 'rgba(59, 130, 246, 0.2)' : 'rgba(255,255,255,0.04)',
                border: filterStatus === tab.id ? '1px solid #3b82f6' : '1px solid rgba(255,255,255,0.06)',
                borderRadius: 20,
                padding: '4px 12px',
                fontSize: 11,
                fontWeight: 700,
                color: filterStatus === tab.id ? '#60a5fa' : '#94a3b8',
                cursor: 'pointer',
                whiteSpace: 'nowrap'
              }}
            >
              {tab.label}
            </button>
          ))}
        </div>

        {/* Signals List */}
        <div style={{ flex: 1, overflowY: 'auto', padding: '16px 20px' }}>
          {filteredSignals.length === 0 ? (
            <div style={{ textAlign: 'center', padding: '40px 0', color: '#64748b' }}>
              <Clock style={{ width: 32, height: 32, margin: '0 auto 10px', opacity: 0.5 }} />
              <div style={{ fontSize: 13, fontWeight: 700 }}>No signals found in this filter</div>
              <div style={{ fontSize: 11, marginTop: 4 }}>Signals are automatically logged when Entry/Exit plans are viewed.</div>
            </div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              {filteredSignals.map(sig => {
                const isTargetHit = sig.status === 'hit_target';
                const isStopHit = sig.status === 'hit_stop';
                const isOpen = sig.status === 'open';
                const retPct = sig.outcome?.returnPct;

                return (
                  <div
                    key={sig.id}
                    style={{
                      background: 'rgba(255,255,255,0.02)',
                      border: isTargetHit
                        ? '1px solid rgba(16, 185, 129, 0.3)'
                        : isStopHit
                          ? '1px solid rgba(239, 68, 68, 0.3)'
                          : '1px solid rgba(255,255,255,0.06)',
                      borderRadius: 12,
                      padding: '12px 14px',
                      display: 'flex',
                      justifyContent: 'space-between',
                      alignItems: 'center',
                      flexWrap: 'wrap',
                      gap: 10
                    }}
                  >
                    <div>
                      <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                        <span style={{ fontSize: 14, fontWeight: 900, color: '#ffffff', fontFamily: 'var(--font-mono)' }}>
                          {sig.symbol}
                        </span>
                        <span style={{
                          background: sig.signalType === 'BUY' ? 'rgba(16, 185, 129, 0.15)' : 'rgba(239, 68, 68, 0.15)',
                          color: sig.signalType === 'BUY' ? '#34d399' : '#f87171',
                          padding: '1px 7px',
                          borderRadius: 4,
                          fontSize: 10,
                          fontWeight: 800
                        }}>
                          {sig.signalType}
                        </span>
                        <span style={{ fontSize: 10, color: '#64748b' }}>
                          📅 {sig.signalDate}
                        </span>
                      </div>
                      <div style={{ fontSize: 10.5, color: '#94a3b8', marginTop: 4 }}>
                        Entry: Rs. {sig.entryPrice} • Target: Rs. {sig.targetPrice || '—'} • Stop: Rs. {sig.stopLoss || '—'}
                      </div>
                      {sig.verdict && (
                        <div style={{ fontSize: 10, color: '#60a5fa', marginTop: 2 }}>
                          {sig.verdict}
                        </div>
                      )}
                    </div>

                    <div style={{ textAlign: 'right' }}>
                      <span style={{
                        background: isTargetHit
                          ? 'rgba(16, 185, 129, 0.15)'
                          : isStopHit
                            ? 'rgba(239, 68, 68, 0.15)'
                            : isOpen
                              ? 'rgba(245, 158, 11, 0.15)'
                              : 'rgba(148, 163, 184, 0.15)',
                        border: isTargetHit
                          ? '1px solid rgba(16, 185, 129, 0.4)'
                          : isStopHit
                            ? '1px solid rgba(239, 68, 68, 0.4)'
                            : isOpen
                              ? '1px solid rgba(245, 158, 11, 0.4)'
                              : '1px solid rgba(148, 163, 184, 0.3)',
                        borderRadius: 20,
                        padding: '2px 9px',
                        fontSize: 10,
                        fontWeight: 800,
                        color: isTargetHit ? '#34d399' : isStopHit ? '#f87171' : isOpen ? '#fbbf24' : '#94a3b8'
                      }}>
                        {sig.status.toUpperCase().replace('_', ' ')}
                      </span>

                      {retPct != null && (
                        <div style={{
                          fontSize: 13,
                          fontWeight: 900,
                          fontFamily: 'var(--font-mono)',
                          color: retPct >= 0 ? '#34d399' : '#f87171',
                          marginTop: 4
                        }}>
                          {retPct >= 0 ? `+${retPct}%` : `${retPct}%`}
                        </div>
                      )}
                      {sig.outcome?.holdingDays && (
                        <div style={{ fontSize: 9.5, color: '#64748b', marginTop: 1 }}>
                          Held {sig.outcome.holdingDays} session(s)
                        </div>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Footer Disclaimer */}
        <div style={{
          padding: '10px 20px',
          background: '#090d16',
          borderTop: '1px solid rgba(255,255,255,0.06)',
          fontSize: 10,
          color: '#64748b',
          textAlign: 'center'
        }}>
          ⚠️ Past performance generated by technical and quantitative filters does not guarantee future market returns. Real execution includes broker commission, SEBON fee, and potential slippage.
        </div>
      </div>
  );

  if (inlineMode) {
    return content;
  }

  return (
    <div style={{
      position: 'fixed',
      top: 0, left: 0, right: 0, bottom: 0,
      background: 'rgba(0,0,0,0.85)',
      backdropFilter: 'blur(8px)',
      zIndex: 9999,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '16px'
    }}>
      {content}
    </div>
  );
}
